# Generated by Django 3.0.3 on 2020-02-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='n/a', max_length=100)),
                ('restaurant_rating', models.CharField(default='n/a', max_length=100)),
                ('restaurant_phone_number', models.CharField(default='n/a', max_length=15)),
                ('restaurant_address', models.TextField(default='n/a')),
                ('type_of_food', models.CharField(default='n/a', max_length=100)),
                ('multiple_restaurant_locations', models.BooleanField(default=False)),
                ('need_directions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(default='n/a', max_length=100)),
                ('restaurant_name', models.CharField(default='n/a', max_length=100)),
                ('dish_rating', models.CharField(default='n/a', max_length=100)),
                ('favorite_dish', models.CharField(default='n/a', max_length=100)),
                ('customer_service_rating', models.CharField(default='n/a', max_length=100)),
                ('dish_picture', models.TextField(default='n/a')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foodies.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(default='n/a', max_length=100)),
                ('commenter_picture', models.TextField(default='n/a')),
                ('comment_heading', models.CharField(default='n/a', max_length=100)),
                ('commenter_location', models.TextField(default='n/a')),
                ('content', models.TextField(default='n/a')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foodies.Review')),
            ],
        ),
    ]
